### ISSUE TITLE
[Android] Compilation errors in library

### ISSUE THREAD

**Issue by tapkain** [KasemJaffer/receive_sharing_intent#132]
```
receive_sharing_intent-1.4.2/android/src/main/kotlin/com/kasem/receive_sharing_intent/ReceiveSharingIntentPlugin.kt: (146, 78): Type mismatch: inferred type is Uri? but Uri was expected
receive_sharing_intent-1.4.2/android/src/main/kotlin/com/kasem/receive_sharing_intent/ReceiveSharingIntentPlugin.kt: (207, 95): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type String?
```

**Comment by francigueco** [comment]
Same problem with 1.4.3 version :(

**Comment by francigueco** [comment]
The error occurs with compileSdkVersion 30. If I put 29 again, in build.gradle, it works fine.

**Comment by LazyDave76** [comment]
i've fired in a PR to try and fix this issue (https://github.com/KasemJaffer/receive_sharing_intent/pull/137)

try adding this to your pubspec.yaml file...
```
receive_sharing_intent:
    git:
      url: https://github.com/LazyDave76/receive_sharing_intent.git
      ref: 7ec782f
```
