### ISSUE TITLE
Kotlin build problem

### ISSUE THREAD

**Issue by proninyaroslav** [KasemJaffer/receive_sharing_intent#144]
Related to https://github.com/KasemJaffer/receive_sharing_intent/pull/137#issuecomment-791989609
 
`1.4.4` version crashes on build:

```
e: /home/yaroslav/.pub-cache/hosted/pub.dartlang.org/receive_sharing_intent-1.4.4/android/src/main/kotlin/com/kasem/receive_sharing_intent/ReceiveSharingIntentPlugin.kt: (146, 78): Type mismatch: inferred type is Uri? but Uri was expected
e: /home/yaroslav/.pub-cache/hosted/pub.dartlang.org/receive_sharing_intent-1.4.4/android/src/main/kotlin/com/kasem/receive_sharing_intent/ReceiveSharingIntentPlugin.kt: (207, 95): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type String?
```

**Comment by proninyaroslav** [comment]
I opened a pull request https://github.com/KasemJaffer/receive_sharing_intent/pull/145

As a temp fix:
```yaml
receive_sharing_intent:
    git:
      url: https://github.com/proninyaroslav/receive_sharing_intent.git
      ref: fix
```
