### ISSUE TITLE
The build gradle version needs to be upgraded

### ISSUE THREAD

**Issue by xshiwei** [KasemJaffer/receive_sharing_intent#256]

**Comment by rsnay** [comment]
There is an open PR that should resolve this: https://github.com/KasemJaffer/receive_sharing_intent/pull/255

I switched to that fork in my app's pubspec.yaml, which worked around the issue:

```yaml
  # Switch back to regular package once https://github.com/KasemJaffer/receive_sharing_intent/issues/256 is resolved
  receive_sharing_intent:
    git:
      url: https://github.com/AyushmanG26/receive_sharing_intent.git
      ref: abedc3d6d5b80df396e9c300fd1a052cbab08827
```
