### ISSUE TITLE
Unable to generate Android build

### ISSUE THREAD

**Issue by SasikumarChinnasamy** [KasemJaffer/receive_sharing_intent#371]
Hi @KasemJaffer ,

I could not generate the Android build due to the issue below.

![Image](https://github.com/user-attachments/assets/c9c2017b-c5f9-4f59-9d1d-eeb8a063807c)

This issue seems to have been fixed with this PR, which was also merged at https://github.com/KasemJaffer/receive_sharing_intent/pull/333. However, the new release has not been published with the issue fixed. Please provide a new release with this update so I can move forward.

Thanks,
sasi.

**Comment by stephensamonte** [comment]
In pubspec.yaml you can reference the github branch as a temporary work around.

It would look something like this:

Replace:
```yaml
#  receive_sharing_intent: ^1.8.1      # Receive shared content from other apps
```

With:
```yaml
receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent.git
      ref: master
```
